name = "HardwareAbstractions"
uuid = "9ac91abb-62f4-42c0-88e8-83732e93d543"
authors = ["Fredrik Bagge Carlson"]
version = "0.1.0"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.8"
ControlSystemsBase = "1"